# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('short_description', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
